export const  INCREASE_COUNTER="INCREASE_COUNTER" //1 ARTTIRMA
export const  DECREASE_COUNTER="DECREASE_COUNTER" //1 AZALTMA
export const  INCREASE_BY_TWO_COUNTER="INCREASE_BY_TWO_COUNTER" //2 ARTTIRMA

